# Generated by Django 5.0.2 on 2024-03-01 18:34

from django.db import migrations

def populate_status(apps, schemaeditor):
    entries = {
        "to do": "An issue that has not yet been started",
        "in progress": "An issue that is activately being worked on",
        "done": "an issue for which work has been completed"
    }
    Status = apps.get_model("issues", "Status")
    for key, value in entries.items():
        status_obj = Status(name=key, description=value)
        status_obj.save()
        
def populate_priority(apps, schemaeditor):
    entries = {
        "low": "A low priority issue",
        "mid": "A medium priority issue",
        "high": "A high priority issue"
    }
    priority = apps.get_model("issues", "Priority")
    for key, value in entries.items():
        priority_obj = priority(name=key, description=value)
        priority_obj.save()



class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_status),
        migrations.RunPython(populate_priority)
    ]


